services:
  openvpn-status:
    hostname: openvpn-status.antizapret
    networks:
      - antizapret_default
    extends:
      file: docker-compose.yml
      service: openvpn-status
    environment:
      - PORT=2000
      - ADMIN_USERNAME=admin!
      - ADMIN_PASSWORD=admin!
#      - BOT_ON=Y
#      - BOT_TOKEN=1
#      - ADMIN_ID=1
#      - HTTPS_ON=Y #Включение HTTPS
#      - DOMAIN_NAME=Test.ru #Указываем имя домена, если оно существует. (при условии включения HTTPS)

# Необходимо пересоздать контейнер dashboard с нижеуказанными настройками
#  dashboard:
#    extends:
#      file: services/dashboard/docker-compose.yml
#      service: dashboard
#    environment:
#      - DASHBOARD_SERVICE_6=OpenVPN Status:6443:openvpn-status.antizapret:2000

networks:
  antizapret_default:
    external: true
    name: antizapret_default