services:
  openstatus-vpn:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: openstatus
    network_mode: host
    ports:
      - "2000:2000" # Хост:контейнер
    environment:
      - PORT=2000
      - ADMIN_USERNAME=Devils
      - ADMIN_PASSWORD=Lvbnhbq04!
      - INSTALL_BOT=Y
      - BOT_TOKEN=8479481675:AAGk0-XER1DquqfYe1eJmAO_TCe_9FsJW70
      - ADMIN_ID=1416781561